application: kenix-nos
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /images/
  static_dir: static/images/
  expiration: 365d

- url: /styles
  static_dir: static/styles

- url: /scripts
  static_dir: static/scripts

- url: /views
  static_dir: static/views

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /.*
  static_files: static/404.html
  upload: static/404.html


libraries:
- name: django
  version: "1.5"

skip_files:

- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?node_modules/.*
- ^(.*/)?app/.*
- ^(.*/)?test/.*
